services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: backend_ecommerce
    volumes:
      - ./mysql:/var/lib/mysql
